<?xml version="1.0"?>
<package format="3">
  <name>semantic_object_nav_rpc</name>
  <version>0.0.1</version>
  <description>Semantic object retrieval from pyslam NPZ map and RPC bridge to Nav2 navigation SDK.</description>
  <maintainer email="robot2@example.com">robot2</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
